[package]
name = "i3bar-river"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
anyhow = "1"
dirs-next = "2"
toml = "0.7"
pangocairo = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
memchr = "2"
thiserror = "1.0.38"

wayrs-client = { version = "0.4", features = ["tokio"] }
wayrs-utils = { version = "0.2", features = ["cursor", "shm_alloc", "seats", "outputs"] }
wayrs-protocols = { version = "0.4", features = ["wlr-layer-shell-unstable-v1", "viewporter", "fractional-scale-v1"] }

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "sync", "io-util", "process"]

[profile.release]
lto = "fat"
strip = true
