[package]
name = "i3bar-river"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dirs-next = "2"
toml = "0.7"
pangocairo = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
memchr = "2"
thiserror = "1.0.38"
futures = "0.3"
signal-hook = "0.3"
signal-hook-tokio = { version = "0.3", features = ["futures-v0_3"] }

wayrs-client = { version = "0.4", features = ["tokio"] }
wayrs-utils = { version = "0.4.0-beta.0", features = ["cursor", "shm_alloc", "seats"] }
wayrs-protocols = { version = "0.4", features = ["wlr-layer-shell-unstable-v1", "viewporter", "fractional-scale-v1"] }

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "sync", "io-util", "process"]

[profile.release]
lto = "fat"
strip = true
