[package]
name = "i3bar-river"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9"
anyhow = "1"
dirs-next = "2"
toml = "0.5"
pangocairo = "0.15"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
memchr = "2"
wayland-client = "0.30.0-beta.10"
wayland-scanner = "0.30.0-beta.10"
wayland-backend = "0.1.0-beta.10"

[dependencies.smithay-client-toolkit]
git = "https://github.com/Smithay/client-toolkit"
default-features = false

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "sync"]

[profile.release]
lto = "fat"
strip = true
