[package]
name = "i3bar-river"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.9"
anyhow = "1"
dirs-next = "2"
toml = "0.5"
pangocairo = "0.16"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
memchr = "2"
thiserror = "1.0.38"

wayrs-client = { version = "0.2.1", features = ["tokio"] }
wayrs-scanner = "0.2"
wayrs-shm-alloc = "0.2"

xcursor = "0.3.4"

[dependencies.tokio]
version = "1"
features = ["macros", "net", "rt", "sync", "io-util", "process"]

[profile.release]
lto = "fat"
strip = true
