[package]
name = "i3bar-river"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
toml = { version = "0.7", default-features = false, features = ["parse"] }
pangocairo = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
memchr = "2"
thiserror = "1.0.38"
signal-hook = { version = "0.3", default-features = false }
nix = "0.26"

wayrs-client = "0.5" 
wayrs-utils = { version = "0.4.0-beta.1", features = ["cursor", "shm_alloc", "seats"] }
wayrs-protocols = { version = "0.5", features = ["wlr-layer-shell-unstable-v1", "viewporter", "fractional-scale-v1"] }

[profile.release]
lto = "fat"
strip = true
